version: "3"
services:
  strapi:
    image: strapi/strapi
    env_file: .env
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    env_file: .env

  site:
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "8000:8000"
